name: Python Tests and Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest 
    - name: Flake8 linting
      run: |
        flake8 --exclude=.git,__pycache__,build,dist,localenv,data,model,screenshots --max-line-length=127 --statistics
    - name: Run tests with pytest
      run: pytest
